; PlatformIO Project Configuration
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Build
build_flags =
    -DCORE_DEBUG_LEVEL=1

; Serial monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Libraries
lib_deps =
    https://github.com/sparkfun/SparkFun_AS726X_Arduino_Library

; Debug
debug_tool = esp-prog
debug_init_break = tbreak setup
